export enum Medicamento {
  morfina = 'Morfina',
  tramadol = 'Tramadol',
  metadona = 'Metadona',
  diazepam = 'Diazepam',
  zolpidem = 'Zolpidem',
  sibutramina = 'Sibutramina',
  testosterona = 'Testosterona',
  fluoxetina = 'Fluoxetina',
  sertralina = 'Sertralina',
  risperidona = 'Risperidona',
  venvanse = 'Venvanse',
  oxicodona = 'Oxicodona',
  ritalina = 'Ritalina',
  lorazepam = 'Lorazepam',
  fenobarbital = 'Fenobarbital',
  alprazolam = 'Alprazolam',
  escitalopram = 'Escitalopram',
  bupropiona = 'Bupropiona',
  desvenlafaxina = 'Desvenlafaxina',
  olanzapina = 'Olanzapina',
  anfepramona = 'Anfepramona',
  buprenorfina = 'Buprenorfina',
  fentanil = 'Fentanil',
  clonazepam = 'Clonazepam',
  mazindol = 'Mazindol',
  benzafetamina = 'Benzafetamina',
  levetiracetam = 'Levetiracetam',
  oxandrolona = 'Oxandrolona',
}

