import { PerguntaInterface } from '../shared/interfaces/perguntas.interface';

export const perguntas: PerguntaInterface[] = [
  {
    id: 1,
    medicamento: 'Morfina',
    grupo: 'Tipo de Receita',
    pergunta: 'Qual é o tipo de receita exigida para Morfina?',
    alternativas: [
      'Notificação de Receita A (amarela)',
      'Receita B1',
      'Receita C1',
      'Receita simples',
    ],
    resposta: 'Notificação de Receita A (amarela)',
  },
  {
    id: 2,
    medicamento: 'Morfina',
    grupo: 'Grupo Farmacológico',
    pergunta: 'A Morfina pertence a qual grupo farmacológico?',
    alternativas: [
      'Opioide forte',
      'Ansiolítico',
      'Antidepressivo',
      'Antipsicótico',
    ],
    resposta: 'Opioide forte',
  },
  {
    id: 3,
    medicamento: 'Morfina',
    grupo: 'Indicação Terapêutica',
    pergunta: 'A Morfina é indicada para qual condição?',
    alternativas: ['Dor intensa', 'Insônia', 'Ansiedade', 'Depressão'],
    resposta: 'Dor intensa',
  },

  {
    id: 4,
    medicamento: 'Tramadol',
    grupo: 'Tipo de Receita',
    pergunta: 'Qual o tipo de receita exigida para Tramadol?',
    alternativas: [
      'Receita de Controle Especial em 2 vias',
      'Receita B1',
      'Notificação A',
      'Receita simples',
    ],
    resposta: 'Receita de Controle Especial em 2 vias',
  },
  {
    id: 5,
    medicamento: 'Tramadol',
    grupo: 'Grupo Farmacológico',
    pergunta: 'Tramadol pertence a qual grupo farmacológico?',
    alternativas: [
      'Opioide fraco',
      'Antipsicótico',
      'Ansiolítico',
      'Antidepressivo',
    ],
    resposta: 'Opioide fraco',
  },
  {
    id: 6,
    medicamento: 'Tramadol',
    grupo: 'Indicação Terapêutica',
    pergunta: 'O Tramadol é indicado principalmente para:',
    alternativas: [
      'Dor moderada a intensa',
      'Insônia',
      'Ansiedade',
      'Convulsões',
    ],
    resposta: 'Dor moderada a intensa',
  },

  {
    id: 7,
    medicamento: 'Metadona',
    grupo: 'Tipo de Receita',
    pergunta: 'Qual tipo de receita é usada para Metadona?',
    alternativas: [
      'Notificação de Receita A (amarela)',
      'Receita B1',
      'Receita simples',
      'Receita C1',
    ],
    resposta: 'Notificação de Receita A (amarela)',
  },
  {
    id: 8,
    medicamento: 'Metadona',
    grupo: 'Grupo Farmacológico',
    pergunta: 'A Metadona pertence a qual grupo farmacológico?',
    alternativas: [
      'Opioide forte',
      'Antipsicótico',
      'Ansiolítico',
      'Anticonvulsivante',
    ],
    resposta: 'Opioide forte',
  },
  {
    id: 9,
    medicamento: 'Metadona',
    grupo: 'Indicação Terapêutica',
    pergunta: 'A Metadona é indicada principalmente para:',
    alternativas: [
      'Dependência de opioides e dor crônica',
      'Obesidade',
      'Insônia',
      'Hipertensão',
    ],
    resposta: 'Dependência de opioides e dor crônica',
  },

  {
    id: 10,
    medicamento: 'Diazepam',
    grupo: 'Tipo de Receita',
    pergunta: 'Qual é o tipo de receita exigida para Diazepam?',
    alternativas: [
      'Receita B1 (azul)',
      'Receita simples',
      'Receita C1',
      'Notificação A',
    ],
    resposta: 'Receita B1 (azul)',
  },
  {
    id: 11,
    medicamento: 'Diazepam',
    grupo: 'Grupo Farmacológico',
    pergunta: 'Diazepam pertence a qual classe?',
    alternativas: [
      'Benzodiazepínico',
      'Opioide',
      'Antipsicótico',
      'Estimulante',
    ],
    resposta: 'Benzodiazepínico',
  },
  {
    id: 12,
    medicamento: 'Diazepam',
    grupo: 'Indicação Terapêutica',
    pergunta: 'Diazepam é indicado para:',
    alternativas: [
      'Ansiedade e convulsões',
      'Depressão',
      'Obesidade',
      'Hipertensão',
    ],
    resposta: 'Ansiedade e convulsões',
  },

  {
    id: 13,
    medicamento: 'Zolpidem',
    grupo: 'Tipo de Receita',
    pergunta: 'Qual o tipo de receita exigida para Zolpidem?',
    alternativas: [
      'Receita C1',
      'Receita B1',
      'Notificação A',
      'Receita simples',
    ],
    resposta: 'Receita C1',
  },
  {
    id: 14,
    medicamento: 'Zolpidem',
    grupo: 'Grupo Farmacológico',
    pergunta: 'Zolpidem pertence a qual grupo?',
    alternativas: [
      'Hipnótico não benzodiazepínico',
      'Opioide',
      'Antipsicótico',
      'Ansiolítico',
    ],
    resposta: 'Hipnótico não benzodiazepínico',
  },
  {
    id: 15,
    medicamento: 'Zolpidem',
    grupo: 'Indicação Terapêutica',
    pergunta: 'Zolpidem é indicado para:',
    alternativas: ['Insônia', 'Depressão', 'Dor crônica', 'Epilepsia'],
    resposta: 'Insônia',
  },

  {
    id: 16,
    medicamento: 'Sibutramina',
    grupo: 'Tipo de Receita',
    pergunta: 'Qual o tipo de receita usada para Sibutramina?',
    alternativas: [
      'Receita B2',
      'Receita B1',
      'Receita simples',
      'Notificação A',
    ],
    resposta: 'Receita B2',
  },
  {
    id: 17,
    medicamento: 'Sibutramina',
    grupo: 'Grupo Farmacológico',
    pergunta: 'A Sibutramina pertence a qual grupo?',
    alternativas: [
      'Inibidor de recaptação de serotonina e noradrenalina',
      'Opioide',
      'Ansiolítico',
      'Antipsicótico',
    ],
    resposta: 'Inibidor de recaptação de serotonina e noradrenalina',
  },
  {
    id: 18,
    medicamento: 'Sibutramina',
    grupo: 'Indicação Terapêutica',
    pergunta: 'A Sibutramina é indicada para:',
    alternativas: [
      'Tratamento da obesidade',
      'Depressão',
      'Ansiedade',
      'Dor neuropática',
    ],
    resposta: 'Tratamento da obesidade',
  },

  {
    id: 19,
    medicamento: 'Testosterona',
    grupo: 'Tipo de Receita',
    pergunta: 'Qual tipo de receita é utilizada para Testosterona?',
    alternativas: [
      'Receita C5',
      'Notificação A',
      'Receita simples',
      'Receita B1',
    ],
    resposta: 'Receita C5',
  },
  {
    id: 20,
    medicamento: 'Testosterona',
    grupo: 'Grupo Farmacológico',
    pergunta: 'A Testosterona pertence a qual grupo farmacológico?',
    alternativas: [
      'Hormônio androgênico',
      'Ansiolítico',
      'Antidepressivo',
      'Antipsicótico',
    ],
    resposta: 'Hormônio androgênico',
  },
  {
    id: 21,
    medicamento: 'Testosterona',
    grupo: 'Indicação Terapêutica',
    pergunta: 'A Testosterona é indicada para:',
    alternativas: [
      'Reposição hormonal masculina',
      'Insônia',
      'Transtorno bipolar',
      'Obesidade',
    ],
    resposta: 'Reposição hormonal masculina',
  },

  {
    id: 22,
    medicamento: 'Fluoxetina',
    grupo: 'Tipo de Receita',
    pergunta: 'Qual tipo de receita é usada para Fluoxetina?',
    alternativas: [
      'Receita simples',
      'Receita B1',
      'Receita C1',
      'Notificação A',
    ],
    resposta: 'Receita simples',
  },
  {
    id: 23,
    medicamento: 'Fluoxetina',
    grupo: 'Grupo Farmacológico',
    pergunta: 'A Fluoxetina é classificada como:',
    alternativas: [
      'Inibidor seletivo de recaptação de serotonina (ISRS)',
      'Benzodiazepínico',
      'Antipsicótico',
      'Opioide',
    ],
    resposta: 'Inibidor seletivo de recaptação de serotonina (ISRS)',
  },
  {
    id: 24,
    medicamento: 'Fluoxetina',
    grupo: 'Indicação Terapêutica',
    pergunta: 'Fluoxetina é indicada principalmente para:',
    alternativas: ['Depressão', 'Dor aguda', 'Insônia', 'Epilepsia'],
    resposta: 'Depressão',
  },

  {
    id: 25,
    medicamento: 'Sertralina',
    grupo: 'Tipo de Receita',
    pergunta: 'Qual o tipo de receita para Sertralina?',
    alternativas: [
      'Receita simples',
      'Receita B1',
      'Receita C1',
      'Notificação A',
    ],
    resposta: 'Receita simples',
  },
  {
    id: 26,
    medicamento: 'Sertralina',
    grupo: 'Grupo Farmacológico',
    pergunta: 'Sertralina é classificada como:',
    alternativas: ['ISRS', 'Opioide', 'Antipsicótico', 'Ansiolítico'],
    resposta: 'ISRS',
  },
  {
    id: 27,
    medicamento: 'Sertralina',
    grupo: 'Indicação Terapêutica',
    pergunta: 'A Sertralina é indicada principalmente para:',
    alternativas: [
      'Depressão e ansiedade',
      'Insônia',
      'Dor crônica',
      'Epilepsia',
    ],
    resposta: 'Depressão e ansiedade',
  },

  {
    id: 28,
    medicamento: 'Risperidona',
    grupo: 'Tipo de Receita',
    pergunta: 'Qual o tipo de receita para Risperidona?',
    alternativas: [
      'Receita C1',
      'Receita simples',
      'Receita B1',
      'Notificação A',
    ],
    resposta: 'Receita C1',
  },
  {
    id: 29,
    medicamento: 'Risperidona',
    grupo: 'Grupo Farmacológico',
    pergunta: 'A Risperidona pertence a qual grupo?',
    alternativas: ['Antipsicótico', 'Ansiolítico', 'Opioide', 'ISRS'],
    resposta: 'Antipsicótico',
  },
  {
    id: 30,
    medicamento: 'Risperidona',
    grupo: 'Indicação Terapêutica',
    pergunta: 'A Risperidona é indicada para:',
    alternativas: [
      'Esquizofrenia e transtorno bipolar',
      'Insônia',
      'Epilepsia',
      'Hipertensão',
    ],
    resposta: 'Esquizofrenia e transtorno bipolar',
  },

  {
    id: 31,
    medicamento: 'Venvanse',
    grupo: 'Tipo de Receita',
    pergunta: 'Qual o tipo de receita necessário para Venvanse?',
    alternativas: [
      'Receita B2',
      'Receita C1',
      'Receita simples',
      'Notificação A',
    ],
    resposta: 'Receita B2',
  },
  {
    id: 32,
    medicamento: 'Venvanse',
    grupo: 'Grupo Farmacológico',
    pergunta: 'Venvanse pertence a qual grupo?',
    alternativas: [
      'Psicoestimulante',
      'Antipsicótico',
      'Ansiolítico',
      'Opioide',
    ],
    resposta: 'Psicoestimulante',
  },
  {
    id: 33,
    medicamento: 'Venvanse',
    grupo: 'Indicação Terapêutica',
    pergunta: 'Venvanse é indicado principalmente para:',
    alternativas: ['TDAH', 'Insônia', 'Depressão', 'Crises convulsivas'],
    resposta: 'TDAH',
  },

  {
    id: 34,
    medicamento: 'Oxicodona',
    grupo: 'Tipo de Receita',
    pergunta: 'Qual tipo de receita é exigida para Oxicodona?',
    alternativas: [
      'Notificação A',
      'Receita B1',
      'Receita simples',
      'Receita C1',
    ],
    resposta: 'Notificação A',
  },
  {
    id: 35,
    medicamento: 'Oxicodona',
    grupo: 'Grupo Farmacológico',
    pergunta: 'A Oxicodona pertence a qual classe?',
    alternativas: [
      'Opioide forte',
      'Ansiolítico',
      'Antipsicótico',
      'Antidepressivo',
    ],
    resposta: 'Opioide forte',
  },
  {
    id: 36,
    medicamento: 'Oxicodona',
    grupo: 'Indicação Terapêutica',
    pergunta: 'Oxicodona é indicada para:',
    alternativas: [
      'Dor intensa',
      'Insônia',
      'Transtorno de ansiedade',
      'Epilepsia',
    ],
    resposta: 'Dor intensa',
  },

  {
    id: 37,
    medicamento: 'Ritalina',
    grupo: 'Tipo de Receita',
    pergunta: 'Qual o tipo de receita exigida para Ritalina?',
    alternativas: [
      'Receita B2',
      'Receita C1',
      'Receita simples',
      'Notificação A',
    ],
    resposta: 'Receita B2',
  },
  {
    id: 38,
    medicamento: 'Ritalina',
    grupo: 'Grupo Farmacológico',
    pergunta: 'Ritalina pertence a qual grupo?',
    alternativas: [
      'Psicoestimulante',
      'Opioide',
      'Benzodiazepínico',
      'Antipsicótico',
    ],
    resposta: 'Psicoestimulante',
  },
  {
    id: 39,
    medicamento: 'Ritalina',
    grupo: 'Indicação Terapêutica',
    pergunta: 'Ritalina é indicada para:',
    alternativas: ['TDAH', 'Depressão', 'Insônia', 'Epilepsia'],
    resposta: 'TDAH',
  },

  {
    id: 40,
    medicamento: 'Lorazepam',
    grupo: 'Tipo de Receita',
    pergunta: 'Qual o tipo de receita usada para Lorazepam?',
    alternativas: [
      'Receita B1',
      'Receita simples',
      'Receita C1',
      'Notificação A',
    ],
    resposta: 'Receita B1',
  },
  {
    id: 41,
    medicamento: 'Lorazepam',
    grupo: 'Grupo Farmacológico',
    pergunta: 'Lorazepam é pertencente ao grupo:',
    alternativas: [
      'Benzodiazepínicos',
      'Opioides',
      'Antipsicóticos',
      'Estimulantes',
    ],
    resposta: 'Benzodiazepínicos',
  },
  {
    id: 42,
    medicamento: 'Lorazepam',
    grupo: 'Indicação Terapêutica',
    pergunta: 'Lorazepam é indicado principalmente para:',
    alternativas: ['Ansiedade', 'Dor intensa', 'TDAH', 'Depressão'],
    resposta: 'Ansiedade',
  },

  {
    id: 43,
    medicamento: 'Fenobarbital',
    grupo: 'Tipo de Receita',
    pergunta: 'Qual o tipo de receita exigida para Fenobarbital?',
    alternativas: [
      'Receita B1',
      'Receita C1',
      'Notificação A',
      'Receita simples',
    ],
    resposta: 'Receita C1',
  },
  {
    id: 44,
    medicamento: 'Fenobarbital',
    grupo: 'Grupo Farmacológico',
    pergunta: 'Fenobarbital pertence a qual grupo?',
    alternativas: ['Barbitúrico', 'Opioide', 'Antipsicótico', 'ISRS'],
    resposta: 'Barbitúrico',
  },
  {
    id: 45,
    medicamento: 'Fenobarbital',
    grupo: 'Indicação Terapêutica',
    pergunta: 'Fenobarbital é indicado para:',
    alternativas: ['Epilepsia', 'Obesidade', 'Insônia leve', 'Depressão'],
    resposta: 'Epilepsia',
  },

  {
    id: 46,
    medicamento: 'Alprazolam',
    grupo: 'Tipo de Receita',
    pergunta: 'Qual o tipo de receita para Alprazolam?',
    alternativas: [
      'Receita B1',
      'Notificação A',
      'Receita C1',
      'Receita simples',
    ],
    resposta: 'Receita B1',
  },
  {
    id: 47,
    medicamento: 'Alprazolam',
    grupo: 'Grupo Farmacológico',
    pergunta: 'Alprazolam pertence a qual grupo?',
    alternativas: [
      'Benzodiazepínico',
      'Opioide',
      'Psicoestimulante',
      'Antidepressivo',
    ],
    resposta: 'Benzodiazepínico',
  },
  {
    id: 48,
    medicamento: 'Alprazolam',
    grupo: 'Indicação Terapêutica',
    pergunta: 'Alprazolam é utilizado para tratar:',
    alternativas: ['Ansiedade', 'Dor intensa', 'Convulsões', 'TDAH'],
    resposta: 'Ansiedade',
  },

  {
    id: 49,
    medicamento: 'Escitalopram',
    grupo: 'Tipo de Receita',
    pergunta: 'Qual o tipo de receita usada para Escitalopram?',
    alternativas: [
      'Receita simples',
      'Receita B1',
      'Receita C1',
      'Notificação A',
    ],
    resposta: 'Receita simples',
  },
  {
    id: 50,
    medicamento: 'Escitalopram',
    grupo: 'Grupo Farmacológico',
    pergunta: 'Escitalopram é classificado como:',
    alternativas: ['ISRS', 'Opioide', 'Antipsicótico', 'Benzodiazepínico'],
    resposta: 'ISRS',
  },
  {
    id: 51,
    medicamento: 'Escitalopram',
    grupo: 'Indicação Terapêutica',
    pergunta: 'Escitalopram é indicado para:',
    alternativas: [
      'Depressão e ansiedade',
      'Dor intensa',
      'Epilepsia',
      'Insônia',
    ],
    resposta: 'Depressão e ansiedade',
  },

  {
    id: 52,
    medicamento: 'Bupropiona',
    grupo: 'Tipo de Receita',
    pergunta: 'Qual tipo de receita é usada para Bupropiona?',
    alternativas: [
      'Receita simples',
      'Receita B2',
      'Notificação A',
      'Receita C1',
    ],
    resposta: 'Receita simples',
  },
  {
    id: 53,
    medicamento: 'Bupropiona',
    grupo: 'Grupo Farmacológico',
    pergunta: 'A Bupropiona pertence a qual grupo?',
    alternativas: [
      'Antidepressivo inibidor de recaptação de noradrenalina e dopamina',
      'Ansiolítico',
      'Opioide',
      'Psicoestimulante',
    ],
    resposta:
      'Antidepressivo inibidor de recaptação de noradrenalina e dopamina',
  },
  {
    id: 54,
    medicamento: 'Bupropiona',
    grupo: 'Indicação Terapêutica',
    pergunta: 'Bupropiona é indicada para:',
    alternativas: [
      'Depressão e cessação do tabagismo',
      'Insônia',
      'Dor crônica',
      'Epilepsia',
    ],
    resposta: 'Depressão e cessação do tabagismo',
  },

  {
    id: 55,
    medicamento: 'Desvenlafaxina',
    grupo: 'Tipo de Receita',
    pergunta: 'Qual o tipo de receita usado para Desvenlafaxina?',
    alternativas: [
      'Receita simples',
      'Receita B1',
      'Receita C1',
      'Notificação A',
    ],
    resposta: 'Receita simples',
  },
  {
    id: 56,
    medicamento: 'Desvenlafaxina',
    grupo: 'Grupo Farmacológico',
    pergunta: 'Desvenlafaxina pertence a qual grupo?',
    alternativas: [
      'Antidepressivo IRSN',
      'Opioide',
      'Ansiolítico',
      'Psicoestimulante',
    ],
    resposta: 'Antidepressivo IRSN',
  },
  {
    id: 57,
    medicamento: 'Desvenlafaxina',
    grupo: 'Indicação Terapêutica',
    pergunta: 'Desvenlafaxina é indicada para:',
    alternativas: ['Depressão', 'Insônia', 'Dor intensa', 'TDAH'],
    resposta: 'Depressão',
  },

  {
    id: 58,
    medicamento: 'Olanzapina',
    grupo: 'Tipo de Receita',
    pergunta: 'Qual tipo de receita é usada para Olanzapina?',
    alternativas: [
      'Receita C1',
      'Receita simples',
      'Receita B1',
      'Notificação A',
    ],
    resposta: 'Receita C1',
  },
  {
    id: 59,
    medicamento: 'Olanzapina',
    grupo: 'Grupo Farmacológico',
    pergunta: 'A Olanzapina pertence a qual grupo?',
    alternativas: ['Antipsicótico', 'Ansiolítico', 'Opioide', 'Antidepressivo'],
    resposta: 'Antipsicótico',
  },
  {
    id: 60,
    medicamento: 'Olanzapina',
    grupo: 'Indicação Terapêutica',
    pergunta: 'Olanzapina é indicada para:',
    alternativas: [
      'Esquizofrenia e transtorno bipolar',
      'Insônia',
      'Epilepsia',
      'Obesidade',
    ],
    resposta: 'Esquizofrenia e transtorno bipolar',
  },

  {
    id: 61,
    medicamento: 'Anfepramona',
    grupo: 'Tipo de Receita',
    pergunta: 'Qual tipo de receita é usada para Anfepramona?',
    alternativas: [
      'Receita B2',
      'Receita simples',
      'Receita B1',
      'Notificação A',
    ],
    resposta: 'Receita B2',
  },
  {
    id: 62,
    medicamento: 'Anfepramona',
    grupo: 'Grupo Farmacológico',
    pergunta: 'Anfepramona pertence a qual grupo?',
    alternativas: ['Anorexígeno', 'Ansiolítico', 'Opioide', 'Antidepressivo'],
    resposta: 'Anorexígeno',
  },
  {
    id: 63,
    medicamento: 'Anfepramona',
    grupo: 'Indicação Terapêutica',
    pergunta: 'Anfepramona é indicada principalmente para:',
    alternativas: ['Obesidade', 'Dor crônica', 'Insônia', 'Epilepsia'],
    resposta: 'Obesidade',
  },

  {
    id: 64,
    medicamento: 'Buprenorfina',
    grupo: 'Tipo de Receita',
    pergunta: 'Qual receita é usada para Buprenorfina?',
    alternativas: [
      'Notificação A',
      'Receita B1',
      'Receita simples',
      'Receita C1',
    ],
    resposta: 'Notificação A',
  },
  {
    id: 65,
    medicamento: 'Buprenorfina',
    grupo: 'Grupo Farmacológico',
    pergunta: 'Buprenorfina é classificada como:',
    alternativas: [
      'Opioide parcial',
      'Estimulante',
      'Ansiolítico',
      'Barbitúrico',
    ],
    resposta: 'Opioide parcial',
  },
  {
    id: 66,
    medicamento: 'Buprenorfina',
    grupo: 'Indicação Terapêutica',
    pergunta: 'A Buprenorfina é indicada para:',
    alternativas: [
      'Dor crônica e dependência de opioides',
      'Insônia',
      'Ansiedade',
      'TDAH',
    ],
    resposta: 'Dor crônica e dependência de opioides',
  },

  {
    id: 67,
    medicamento: 'Fentanil',
    grupo: 'Tipo de Receita',
    pergunta: 'Qual tipo de receita é obrigatório para Fentanil?',
    alternativas: [
      'Notificação A',
      'Receita B1',
      'Receita simples',
      'Receita C1',
    ],
    resposta: 'Notificação A',
  },
  {
    id: 68,
    medicamento: 'Fentanil',
    grupo: 'Grupo Farmacológico',
    pergunta: 'Fentanil pertence a qual grupo?',
    alternativas: [
      'Opioide forte',
      'Ansiolítico',
      'Antipsicótico',
      'Estimulante',
    ],
    resposta: 'Opioide forte',
  },
  {
    id: 69,
    medicamento: 'Fentanil',
    grupo: 'Indicação Terapêutica',
    pergunta: 'O Fentanil é indicado principalmente para:',
    alternativas: ['Dor intensa', 'Ansiedade', 'Insônia', 'TDAH'],
    resposta: 'Dor intensa',
  },

  {
    id: 70,
    medicamento: 'Clonazepam',
    grupo: 'Tipo de Receita',
    pergunta: 'Qual tipo de receita é usado para Clonazepam?',
    alternativas: [
      'Receita B1',
      'Receita simples',
      'Receita C1',
      'Notificação A',
    ],
    resposta: 'Receita B1',
  },
  {
    id: 71,
    medicamento: 'Clonazepam',
    grupo: 'Grupo Farmacológico',
    pergunta: 'Clonazepam pertence a qual grupo?',
    alternativas: [
      'Benzodiazepínico',
      'Opioide',
      'Ansiolítico não benzodiazepínico',
      'Antidepressivo',
    ],
    resposta: 'Benzodiazepínico',
  },
  {
    id: 72,
    medicamento: 'Clonazepam',
    grupo: 'Indicação Terapêutica',
    pergunta: 'O Clonazepam é indicado principalmente para:',
    alternativas: [
      'Convulsões e ansiedade',
      'Insônia leve',
      'Dor crônica',
      'Obesidade',
    ],
    resposta: 'Convulsões e ansiedade',
  },

  {
    id: 73,
    medicamento: 'Mazindol',
    grupo: 'Tipo de Receita',
    pergunta: 'Qual o tipo de receita usado para Mazindol?',
    alternativas: ['Receita B2', 'Receita B1', 'Receita C1', 'Receita simples'],
    resposta: 'Receita B2',
  },
  {
    id: 74,
    medicamento: 'Mazindol',
    grupo: 'Grupo Farmacológico',
    pergunta: 'Mazindol pertence a qual grupo?',
    alternativas: ['Anorexígeno', 'Ansiolítico', 'Opioide', 'Antidepressivo'],
    resposta: 'Anorexígeno',
  },
  {
    id: 75,
    medicamento: 'Mazindol',
    grupo: 'Indicação Terapêutica',
    pergunta: 'Mazindol é indicado para:',
    alternativas: ['Obesidade', 'Insônia', 'Dor neuropática', 'Epilepsia'],
    resposta: 'Obesidade',
  },

  {
    id: 76,
    medicamento: 'Benzafetamina',
    grupo: 'Tipo de Receita',
    pergunta: 'Qual tipo de receita é usada para Benzafetamina?',
    alternativas: ['Receita B2', 'Receita C1', 'Receita simples', 'Receita B1'],
    resposta: 'Receita B2',
  },
  {
    id: 77,
    medicamento: 'Benzafetamina',
    grupo: 'Grupo Farmacológico',
    pergunta: 'Benzafetamina pertence a qual grupo?',
    alternativas: ['Anorexígeno', 'Ansiolítico', 'Opioide', 'Antidepressivo'],
    resposta: 'Anorexígeno',
  },
  {
    id: 78,
    medicamento: 'Benzafetamina',
    grupo: 'Indicação Terapêutica',
    pergunta: 'A Benzafetamina é indicada principalmente para:',
    alternativas: ['Obesidade', 'Depressão', 'Insônia', 'Epilepsia'],
    resposta: 'Obesidade',
  },

  {
    id: 79,
    medicamento: 'Levetiracetam',
    grupo: 'Tipo de Receita',
    pergunta: 'Qual tipo de receita é usada para Levetiracetam?',
    alternativas: [
      'Receita simples',
      'Receita B1',
      'Receita C1',
      'Notificação A',
    ],
    resposta: 'Receita simples',
  },
  {
    id: 80,
    medicamento: 'Levetiracetam',
    grupo: 'Grupo Farmacológico',
    pergunta: 'O Levetiracetam pertence a qual grupo?',
    alternativas: [
      'Anticonvulsivante',
      'Ansiolítico',
      'Opioide',
      'Psicoestimulante',
    ],
    resposta: 'Anticonvulsivante',
  },
  {
    id: 81,
    medicamento: 'Levetiracetam',
    grupo: 'Indicação Terapêutica',
    pergunta: 'Levetiracetam é indicado para:',
    alternativas: ['Crises epilépticas', 'Depressão', 'Insônia', 'Obesidade'],
    resposta: 'Crises epilépticas',
  },

  {
    id: 82,
    medicamento: 'Oxandrolona',
    grupo: 'Tipo de Receita',
    pergunta: 'Qual o tipo de receita usada para Oxandrolona?',
    alternativas: ['Receita C5', 'Receita B1', 'Receita simples', 'Receita C1'],
    resposta: 'Receita C5',
  },
  {
    id: 83,
    medicamento: 'Oxandrolona',
    grupo: 'Grupo Farmacológico',
    pergunta: 'A Oxandrolona pertence a qual grupo?',
    alternativas: [
      'Esteroide anabolizante',
      'Opioide',
      'Ansiolítico',
      'Antidepressivo',
    ],
    resposta: 'Esteroide anabolizante',
  },
  {
    id: 84,
    medicamento: 'Oxandrolona',
    grupo: 'Indicação Terapêutica',
    pergunta: 'A Oxandrolona é indicada para:',
    alternativas: [
      'Ganhos de massa magra e recuperação de queimados',
      'Insônia',
      'Ansiedade',
      'Epilepsia',
    ],
    resposta: 'Ganhos de massa magra e recuperação de queimados',
  },

  {
    id: 85,
    medicamento: 'Fluoxetina',
    grupo: 'Tipo de Receita',
    pergunta: 'Qual o tipo de receita para Fluoxetina?',
    alternativas: [
      'Receita simples',
      'Receita B1',
      'Receita C1',
      'Notificação A',
    ],
    resposta: 'Receita simples',
  },
  {
    id: 86,
    medicamento: 'Fluoxetina',
    grupo: 'Grupo Farmacológico',
    pergunta: 'A Fluoxetina pertence ao grupo:',
    alternativas: ['ISRS', 'Ansiolítico', 'Opioide', 'Antipsicótico'],
    resposta: 'ISRS',
  },
  {
    id: 87,
    medicamento: 'Fluoxetina',
    grupo: 'Indicação Terapêutica',
    pergunta: 'Fluoxetina é indicada para:',
    alternativas: ['Depressão', 'Insônia', 'Epilepsia', 'Hipertensão'],
    resposta: 'Depressão',
  },

  {
    id: 88,
    medicamento: 'Sertralina',
    grupo: 'Tipo de Receita',
    pergunta: 'Qual o tipo de receita usado para Sertralina?',
    alternativas: ['Receita simples', 'Receita B1', 'Receita C1', 'Receita B2'],
    resposta: 'Receita simples',
  },
  {
    id: 89,
    medicamento: 'Sertralina',
    grupo: 'Grupo Farmacológico',
    pergunta: 'Sertralina pertence a qual grupo?',
    alternativas: ['ISRS', 'Ansiolítico', 'Antipsicótico', 'Opioide'],
    resposta: 'ISRS',
  },
  {
    id: 90,
    medicamento: 'Sertralina',
    grupo: 'Indicação Terapêutica',
    pergunta: 'A Sertralina é indicada principalmente para:',
    alternativas: ['Depressão e ansiedade', 'Dor intensa', 'Epilepsia', 'TDAH'],
    resposta: 'Depressão e ansiedade',
  },
];
